# ==================================================================================
# DOCKER COMPOSE FOR MARKER3 - SIMPLIFIED WITH BUILT-IN MODEL MANAGEMENT
# ==================================================================================
# Modes: dev-open → dev-secure → production
# Uses marker's built-in model management (no custom scripts)
# Docker Desktop compatible networking + RTX 5090 optimized
# ==================================================================================

version: '3.8'

services:

  # Development Open: First-time setup and model downloads
  marker-dev-open:
    image: marker3:rtx5090-dev-full
    container_name: marker3-dev-open
    profiles: [dev-open, first-run]
    volumes:
      - ./cache:/home/appuser/.cache  # Host directory for model cache (better permissions)
      - ./data:/app/data:rw
      - ./output:/app/output:rw
      # Live code editing for development
      - ./marker:/app/marker:rw
      - ./scripts:/app/scripts:rw
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
      - HF_HUB_OFFLINE=0         # Allow model downloads
      - TRANSFORMERS_OFFLINE=0   # Allow model downloads
      - NETWORK_MODE=open
      - PYTHONPATH=/app
      - FASTAPI_RELOAD=true      # Enable hot reload for development
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"  # FastAPI server
      - "8501:8501"  # Streamlit UI
    command: python -c "from marker.scripts.server import server_cli; server_cli(['--host', '0.0.0.0', '--port', '8000'])"
    healthcheck:
      test: ["CMD", "python", "-c", "import marker; print('Dev-open ready')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # Longer startup time for model downloads

  # Development Secure: Live code editing with network restrictions
  marker-dev-secure:
    image: marker3:rtx5090-dev-full
    container_name: marker3-dev-secure
    profiles: [dev-secure, dev]
    volumes:
      - ./cache:/home/appuser/.cache  # Host directory for model cache
      - ./data:/app/data:rw
      - ./output:/app/output:rw
      # Live code editing for development
      - ./marker:/app/marker:rw
      - ./scripts:/app/scripts:rw
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
      - HF_HUB_OFFLINE=1         # Secure - use cached models only
      - TRANSFORMERS_OFFLINE=1   # Secure - no external access
      - NETWORK_MODE=secure
      - PYTHONPATH=/app
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"  # FastAPI server
      - "8501:8501"  # Streamlit UI
    command: python -c "from marker.scripts.server import server_cli; server_cli(['--host', '0.0.0.0', '--port', '8000'])"
    healthcheck:
      test: ["CMD", "python", "-c", "import marker; print('Dev-secure ready')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Production Mode: Maximum security, baked-in code
  marker-production:
    image: marker3:rtx5090-dev-full
    container_name: marker3-production
    profiles: [production]
    volumes:
      - marker_cache:/home/appuser/.cache  # Read-only cached models
      - ./data:/app/data:rw
      - ./output:/app/output:rw
      # NO source code mounts - uses baked-in code only
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
      - HF_HUB_OFFLINE=1         # Maximum security - use cached models only
      - TRANSFORMERS_OFFLINE=1   # Maximum security - no external access
      - NETWORK_MODE=production
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"
    command: python -c "from marker.scripts.server import server_cli; server_cli(['--host', '0.0.0.0', '--port', '8000'])"
    # Maximum security hardening
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=1G
    healthcheck:
      test: ["CMD", "python", "-c", "import marker; print('Production ready')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Docker Desktop Compatible Networking
# Uses default bridge network for maximum compatibility
networks:
  default:
    driver: bridge
    # Docker Desktop's built-in network - most reliable

# Persistent data storage
volumes:
  marker_cache:
    driver: local  # Persistent cache for marker's built-in model management
  data:
    driver: local
  output:
    driver: local
